[package]
name = "cw-token"
description = "Trait implementations for abstracting out token handling"
version = "0.1.0"
authors = ["Apollo Devs"]
edition = "2021"
repository = "https://github.com/apollodao/cw-token"

[workspace]

[dependencies]
osmosis-std = { git = "https://github.com/osmosis-labs/osmosis-rust.git" }
cosmwasm-std = { version = "1.1", features = ["stargate", "cosmwasm_1_1"] }
cw20 = "0.16"
cw20-base = { version = "0.16", features = ["library"] }
cw-storage-plus = "0.16"
schemars = "0.8.8"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }
thiserror = {version = "1.0.37"}
cw-asset = "2.3"
cosmwasm-schema = { version = "1.1" }
cw-utils = "0.16"
