[package]
name = "cw-token"
description = "Trait implementations for abstracting out token handling"
version = "0.1.0"
authors = ["Apollo Devs"]
edition = "2021"
repository = "https://github.com/apollodao/cw-token"


[dependencies]
apollo-proto-rust = { tag = "v0.1.0", git = "https://github.com/apollodao/apollo-proto-rust" }
cosmwasm-std = { version="1.0", features = ["stargate"] }
cw20 = "^0.14"
cw20-base = "^0.14"
cw-storage-plus = "^0.14"
schemars = "0.8.1"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }
thiserror = {version = "1.0.31"}
cw-asset = "^2.3.0"
