[package]
name = "cw-token"
description = "Trait implementations for abstracting out token handling"
version = "0.1.0"
authors = ["Apollo Devs"]
edition = "2021"
repository = "https://github.com/apollodao/cw-token"


[dependencies]
osmosis-std = { git = "https://github.com/osmosis-labs/osmosis-rust.git" }
apollo-proto-rust = { tag = "v0.3.1", git = "https://github.com/apollodao/apollo-proto-rust" }
cosmwasm-std = { version = "1.1.0", features = ["stargate"] }
cw20 = "0.15.0"
cw20-base = { version = "0.15", features = ["library"] }
cw-storage-plus = "0.15"
schemars = "0.8.8"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }
thiserror = {version = "1.0.31"}
cw-asset = "2.3.0"
cosmwasm-schema = { version = "1.1.0" }
cw-utils = "0.15.0"
