[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true

[tasks.format]
toolchain = "nightly"
install_crate = { crate_name = "rustfmt-nightly", rustup_component_name = "rustfmt-preview", binary = "rustfmt", test_arg = "--help" }
command = "cargo"
args = ["fmt", "--", "--emit=files","--verbose"]

[tasks.clean]
command = "cargo"
args = ["clean "]

[tasks.build]
command = "cargo"
args = ["build", "--release"]
dependencies = ["clean"]

[tasks.test]
command = "cargo"
args = ["test"]
dependencies = ["clean"]

[tasks.cov]
command = "cargo"
args = [
    "tarpaulin",
    "--ignore-tests",
    "--out Lcov",
    "--output-dir target/tarpaulin",
]

[tasks.all]
dependencies = ["clean", "format", "build", "test", "cov"]
